void modulo(int x, int N);
void ctrlSpeed(int *temps);
void rules();
void afficherFleche(int i);
void bougerMenu(int i);
void bougerSpeed(unsigned long int *temps, int j);
void lvl1();
void lvl2();
void PremierEcran();
void menuOption();
void bougerMenu(int i);
void afficherFleche(int i);
int modulo(int x,int N);
void lvl1(char *key, int *temps, int *score, Pcman *pcm, Pcman ennemi[4], Objet diamants[5], int tab[20][50], int longueurTab,int largeurTab);
void lvl2(char *key, int *temps, int *score, Pcman *pcm, Pcman ennemi[4], Objet diamants[5], int tab[20][50], int longueurTab,int largeurTab);
void lvl3(char *key, int *temps, int *score, Pcman *pcm, Pcman ennemi[4], Objet diamants[5], int tab[20][50], int largeurTab,int longueurTab);
